[package]
name = "heo_token"
version = "0.1.0"
description = "HEO Token Economics - Reward validators and experiment reusers"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "heo_token"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
anchor-spl = "0.30.1" 